// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgdyuwhqfovefdiszouc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnZHl1d2hxZm92ZWZkaXN6b3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTc2MTEsImV4cCI6MjA2NDA3MzYxMX0.oa5VS7yUi0IWltPBmz6HH0_z71HHARf-2S-yq0uWaRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);